#!/usr/bin/env python3
"""Construye el cap 14 «El horizonte se acorta» (Bloque IV) usando el
esqueleto del cap 3. Prosa corrida (sin subtítulos de sección), con citas
cortas de Ammous incrustadas en el flujo (no en bloque)."""
import re

EYEBROW = "Primera consecuencia · la raíz"
TITLE = "El horizonte se acorta"
SUBTITLE = "Avanzamos hacia el abismo porque el futuro dejó de pesar lo que pesaba"

# Items (sin secciones):
#   ("lead", texto)        → primer párrafo con capital
#   "texto"                → párrafo normal
CONTENT = [
    ("lead", 'Pregúntele a alguien que hoy tenga ochenta años qué esperaba de la vida cuando era joven, y le contestará en décadas. Esperaba un oficio para quedarse en él hasta el final —no un trabajo, un oficio—. Una casa que sería suya y después de sus hijos. Hijos criados sin prisa, a lo largo de veinte años. Esperaba plantar árboles a cuya sombra sabía que no se sentaría, y le parecía lo más natural del mundo hacerlo. Su horizonte —la distancia hasta donde alcanzaba a mirar cuando hacía planes— se medía en generaciones.'),

    'Pregúntele lo mismo a alguien de veinte años hoy, y le contestará en meses. No por falta de ambición: por sentido común. Buscará lo que rinda pronto, lo que no lo ate, lo que pueda soltar si las cosas cambian —porque da por sentado que cambiarán—. Comprar una casa le parece una idea de otra época. Quedarse treinta años en un oficio, una condena más que una meta. Plantar un árbol para sus nietos no le pasa por la cabeza, y si se lo propusieran, la pregunta honesta sería: ¿para qué? Su horizonte se mide en lo que se ve desde aquí hasta el final del año.',

    'Es tentador leer esto como una historia de decadencia: los viejos eran de otra madera, los jóvenes de hoy no aguantan nada. Resista la tentación, porque es falsa y además le impediría ver lo único que importa. Ninguna generación nace peor que la anterior. Y que quede claro: el mundo del abuelo no era mejor —vivió dictaduras, hiperinflaciones que arrasaron lo ahorrado, carencias y encierros que el joven de hoy no toleraría un mes—. No le pintemos una edad de oro. El punto es justamente el contrario, y es más inquietante: aquel abuelo, en un mundo más duro y más incierto que el de su nieto, todavía plantaba a treinta años. El joven de hoy, que vive más seguro, más libre y con más opciones que ninguna generación anterior, mira más corto que él. La materia humana es la misma —la misma capacidad de esperar, de sacrificarse, de mirar lejos—. Si su abuelo, con veinte años, hubiera enfrentado exactamente las cuentas que este joven enfrenta, habría decidido igual que él. Y si el joven de hoy hubiera nacido en el mundo del abuelo, plantaría árboles sin pensarlo.',

    'Entonces, si la gente no cambió, ¿qué cambió? Cambió la cuenta. No la naturaleza humana, sino la aritmética silenciosa que cada uno hace, sin darse cuenta de que la hace, cada vez que decide cuánto futuro vale la pena tener en cuenta. Esa cuenta —cuánto pesa el mañana frente al hoy— alguien se la torció a una generación entera a la vez. No los hizo peores. Les cambió los números con que deciden, y con otros números, las mismas personas deciden distinto.',

    'Lo inquietante es que casi nadie eligió esto. Nadie despertó un día y resolvió mirar más corto. El horizonte se les encogió por debajo, despacio, sin aviso —como se encoge una cosa que nadie está vigilando—. Y aquí está la pregunta de la que cuelga todo lo que viene: ¿qué tiene el poder de cambiarle la cuenta, a la vez, a millones de personas que no se conocen ni se pusieron de acuerdo? ¿Qué les torció a todos, en silencio, el peso del futuro?',

    'Para verlo, piense primero en todo lo que un ser humano hace que solo tiene sentido si el futuro va a llegar. Plantar un árbol que dará sombra a quien todavía no nace. Criar un hijo con paciencia, sabiendo que el fruto de esa crianza tardará veinte años en verse. Levantar una empresa que no dará ganancias hasta dentro de una década. Cuidar un suelo para que siga alimentando a los nietos. Estudiar largos años para dominar un oficio. Comprar una casa para pagarla en treinta. Cada una de estas cosas es una espera larga sostenida en el tiempo, y todas, sin excepción, descansan sobre lo mismo: sobre que alguien se haya privado hoy de consumir —que haya salvado un pedazo del mundo en vez de gastárselo— para que ese pedazo sostenga el proyecto hasta que madure. Eso es ahorrar: no guardar dinero, sino apartar del consumo de hoy los recursos reales que el mañana necesitará. Y el dinero no es ese ahorro; es el vehículo donde el ahorro se guarda y viaja hasta el futuro —el título que conserva su derecho sobre el pedazo del mundo que salvó—. De modo que todo proyecto largo descansa sobre dos cosas, no una: que alguien se prive hoy, y que el vehículo donde guarda esa privación no se le pudra antes de la cosecha. Si el dinero conserva su valor, el pedazo del mundo llega entero a destino y el proyecto es pensable. Si el dinero se diluye, el vehículo tiene una fuga: el pedazo del mundo se escurre por el camino, aunque la privación haya sido real, y el proyecto largo deja de tener con qué sostenerse. El dinero no crea la paciencia ni hace el ahorro —eso lo pone quien se priva—; pero decide si esa paciencia llega intacta al final del camino o se evapora antes. Por eso no es un asunto más entre otros: es la vara con que se mide cuánto futuro es posible.',

    'Y en ningún lugar se ve esto tan de cerca como en la cosa que el lector más joven palpa en carne propia, porque ahí la cuenta encogida no necesita teoría. Hay un consejo que durante décadas pasó de padres a hijos en casi toda América Latina, dicho con la certeza de quien transmite una verdad evidente: <em>compre una casa, mijo, que eso siempre se valoriza</em>. No era un consejo de inversionistas; era sabiduría doméstica, de sobremesa, repetida por gente que jamás abrió un libro de economía. Y tenían razón —la casa, en efecto, se valorizaba año tras año, década tras década—. Lo que casi nadie veía era por qué.',

    'Porque la casa no estaba subiendo. Era el dinero el que se hundía debajo de ella. Recuerde lo que ya vimos: un dinero que se diluye sin freno convierte el ahorro en moneda en una forma lenta de perder. Y la gente, sin necesidad de que nadie se lo explicara, lo aprendió en la única escuela que enseña de verdad, la de ver evaporarse lo guardado. Así que hizo lo sensato: dejó de guardar valor en una moneda que se derretía y empezó a guardarlo en algo que el dinero no podía diluir —ladrillo, cemento, tierra—. La casa dejó de ser, en la cabeza de millones, un lugar donde vivir, y pasó a ser lo que la moneda ya no podía ser: una caja fuerte que no goteaba.',

    'Y aquí empieza el bucle que lo cambia todo. Cuando millones de personas huyen al mismo refugio, el refugio se encarece. No porque hagan falta más casas para vivir —la gente no necesitaba de pronto tres techos—, sino porque la casa se había vuelto el depósito de valor que el dinero dejó de ser. El que tenía con qué compraba una para habitarla y otras para guardar en ellas; vivía en una y arrendaba el resto, no por codicia, sino porque era el único cofre disponible que no se vaciaba solo. Cada casa comprada para atesorar era una casa menos para habitar, y un empujón más al precio de todas. El refugio se infló a fuerza de gente refugiándose en él.',

    'Ahora mire al joven de hoy, parado frente a ese precio. Él no vivió la inflación que ahuyentó a sus abuelos del dinero; nació después, cuando el polvo ya se había asentado. Pero heredó el resultado: una casa que cuesta, medida en años de su salario, varias veces lo que le costó a su padre la suya. No hizo nada mal, igual que el viejo que ahorró toda su vida no hizo nada mal. Simplemente llegó tarde a un cofre que ya estaba lleno de los ahorros que otros metieron huyendo de la moneda. La casa —que para sus padres fue la prueba de que el esfuerzo largo rendía, el ancla de toda una vida de planes— se le cerró antes de que pudiera siquiera intentarlo.',

    'Y fíjese en lo que eso le hace a su cuenta del futuro, porque es el corazón de todo el capítulo. La casa no era solo un techo: era el eje alrededor del cual se organizaba el horizonte largo de una vida. Uno compraba la casa pensando a treinta años, y esos treinta años de pagarla ordenaban todo lo demás —quedarse en un oficio, echar raíces en un lugar, criar hijos con la mira puesta lejos—. Quítele la casa posible, y no le quita solo un edificio: le quita la razón para calcular a treinta años. ¿Para qué mirar tan lejos, para qué atarse, para qué esperar, si lo que anclaba esa espera —el techo propio, el patrimonio que dura— se volvió inalcanzable? El joven no se volvió impaciente por capricho. Se volvió impaciente porque le cerraron la puerta del futuro largo que sus padres sí pudieron cruzar, y nadie planea a treinta años en una casa que sabe que nunca tendrá.',

    'Vea entonces lo que hizo el dinero, saltando de una generación a otra y cambiando de disfraz en el camino. En los padres fue defensa: compraban ladrillo para que la inflación no les comiera el fruto del trabajo. En los hijos es exclusión: no llegan a tener qué defender, porque el precio que la defensa de sus padres infló los dejó afuera. La misma falsificación monetaria, una sola, produjo las dos cosas —y la segunda es la más honda, porque no le roba a alguien lo que guardó: le roba, a una generación entera, la posibilidad misma de guardar a largo plazo—. La herida no fue la inflación que vivieron los abuelos. Fue lo que esa inflación le hizo a la cuenta de los nietos.',

    'Pero sería un error cerrar aquí, pensando que esto es una historia sobre vivienda. La casa es solo la ventana por la que el joven toca con la mano algo mucho más grande —el primer lugar donde el horizonte encogido se vuelve visible, porque tiene un precio escrito y un salario que no alcanza—. La herida, sin embargo, no está en el mercado inmobiliario. Está en la cuenta misma, y esa cuenta gobierna mucho más que el techo.',

    'Porque el mismo dinero que le cerró la casa al joven le está acortando el cálculo en todo lo demás, y no solo a él: a la sociedad entera. Una sociedad cuyo dinero castiga la espera no acorta el horizonte en un solo renglón de la vida —lo acorta en todos a la vez—. Deja de plantar lo que tarda. Deja de cuidar lo que solo rinde a largo plazo. Deja de construir lo que no se cosecha pronto. No por un acuerdo, no por una orden, no porque a alguien se le ocurriera —sino porque a cada uno, por separado, la cuenta le empezó a salir igual: el futuro no compensa, tome lo de hoy—. Millones de cuentas privadas, todas torcidas en la misma dirección por la misma causa silenciosa, suman el horizonte encogido de una civilización entera.',

    'Y eso deja marcas en el mundo —marcas que usted ha visto, aunque nunca las haya atado a su origen—. Las verá en un hombre que tala el nogal que su padre plantó, no por maldad sino porque la cuenta se lo aconseja. En otro que exprime su tierra hasta dejarla muerta, sabiendo que la mata. En bosques que caen, en suelos que se vacían, en guerras que se financian con dinero que nadie aceptaría pagar de frente. Cada una parece un problema distinto, con sus propios culpables y sus propias soluciones. No lo son. Son la misma cuenta falseada saliendo por ventanas distintas. La vivienda fue la primera, la que el joven mira de cerca; las que vienen están más lejos de su vista, pero salen del mismo lugar.',

    'Es hora de nombrar lo que el gancho dejó en suspenso. ¿Qué tiene el poder de torcerle la cuenta, a la vez, a millones de personas que no se conocen? La respuesta es la misma que ha recorrido todo este libro, solo que ahora la veremos hacer algo que hasta aquí no le habíamos visto hacer.',

    'A lo largo de todo el recorrido anterior, el dinero malo cometió siempre el mismo crimen: falsificar señales. Torció la tasa de interés, deformó los precios, escondió las pérdidas, diluyó el ahorro. En cada caso, el daño consistía en mentir —en hacer que una señal dijera algo falso sobre el mundo—. Pero había un supuesto silencioso debajo de todo eso: que existía alguien capaz de leer la señal, alguien con la cabeza puesta lo bastante lejos como para que mentirle tuviera sentido. Toda la primera mitad del daño da por hecho que el lector de la señal todavía mira hacia el futuro.',

    'Aquí está el segundo golpe, el que no habíamos visto, y es más hondo que el primero. El dinero malo no solo falsifica las señales que una sociedad lee sobre el futuro. Cambia cuánto le importa el futuro a esa sociedad, para empezar. No solo ensucia el mensaje: enferma al que lo lee. Y lo hace por un mecanismo que ya conoce, solo que nunca lo habíamos seguido hasta esta consecuencia. Un dinero que se preserva en el tiempo premia al que espera —guardar es ganar—, y premiar la espera, repetido sobre millones de personas durante generaciones, va inclinando hacia abajo la preferencia temporal de un pueblo entero: lo vuelve más paciente, más capaz de mirar lejos. Un dinero que se diluye hace lo contrario: castiga al que espera, y empuja a todos —en palabras de Ammous— a volverse “propensos a gastarla o a pedirla prestada”. No es un consejo que la gente decida seguir; es la dirección hacia la que el suelo entero se inclina bajo sus pies.',

    'Ammous lo dice sin rodeos, y conviene leerlo con cuidado porque invierte el orden con que solemos pensar la historia: el dinero sólido, escribe, preserva el valor en el tiempo, “lo que proporciona a la gente mayor incentivo para pensar en el futuro, y disminuye su preferencia temporal”, y “la reducción de la preferencia temporal es lo que inicia el proceso de civilización humana”. Léalo al revés y tiene la herida de este capítulo: si el dinero que baja la preferencia temporal es el que enciende la civilización, el dinero que la sube es el que la apaga. No metafóricamente. Por el mismo mecanismo, andando hacia atrás.',

    'Conviene detenerse aquí, antes de seguir, para decir con precisión lo que se afirma y lo que no. La preferencia temporal de una sociedad no tiene una sola causa. La sube una guerra, que vuelve insensato pensar en diez años cuando no se sabe si habrá mañana. La sube el caos, la inseguridad, la enfermedad, todo lo que vuelve el futuro incierto —y eso el propio análisis austriaco lo reconoce sin reparos—. El dinero no es la única mano que empuja el horizonte. Pero es una mano distinta de todas las demás, y por tres razones que ninguna otra reúne a la vez. Empuja a todos en la misma dirección —no a unos hacia la paciencia y a otros hacia la prisa, como hace la cultura, sino a la sociedad entera del mismo lado—. Empuja sin descanso, todos los días, no en el sobresalto de una crisis que pasa, sino en el goteo constante de una moneda que se diluye mientras la gente duerme. Y empuja sin que nadie lo vea, porque a diferencia de la guerra o la peste, que gritan, la degradación del dinero es muda. El horizonte no lo regala una época próspera ni lo arruina una época dura —las generaciones que miraban más lejos cargaban guerras y tiranías, y aun así plantaban a largo plazo—; lo que sostiene el horizonte es un dinero que no castiga la paciencia. No es la única causa del horizonte corto. Es la única que cumple, a la vez, las condiciones para torcerle la cuenta a una civilización entera sin que ella se entere.',

    'Esto responde directo a la pregunta que dejó abierta el comienzo —qué tiene el poder de cambiarle la cuenta, a la vez, a millones que no se conocen—. La respuesta honesta no es “solo el dinero”; es que el dinero es lo único de su clase: la única palanca universal, constante e invisible.',

    'Y hay un detalle que vuelve esto peor de lo que parece a primera vista: el efecto no se queda quieto, se realimenta. Ammous recoge la observación de Hans-Hermann Hoppe de que, una vez que la preferencia temporal de una sociedad cae lo suficiente como para permitir que se acumule capital, la tendencia es que caiga todavía más —se entra en una espiral virtuosa, un “proceso de civilización” que se alimenta a sí mismo—. Pero toda espiral que sube puede bajar. Si el dinero degradado empuja la preferencia temporal hacia arriba, no la empuja una vez y se detiene: enciende la espiral en reversa. Cada grado de impaciencia hace más difícil ahorrar, y cada ahorro que no ocurre hace a la sociedad un grado más impaciente. La civilización no se apaga de golpe; se desenrosca.',

    'Aquí debo ser honesto con usted sobre dónde termina lo que Ammous afirma y dónde empieza lo que este libro le suma. Ammous describe el doble efecto y la espiral; lo que añadimos en este capítulo es seguir esa espiral a través de las generaciones, hasta el joven del comienzo. Porque la parte más cruel del mecanismo es justamente la que no se ve dentro de una sola vida. El que vivió la inflación al menos supo que algo le estaban haciendo —vio diluirse lo suyo, sintió el robo—. El que nace después no siente nada: hereda una preferencia temporal alta como quien hereda el color de los ojos, sin sospechar que es el sedimento de una falsificación que ocurrió antes de que él llegara. Recibe el horizonte ya encogido y lo toma por el tamaño natural del mundo. No sabe que sus abuelos miraban más lejos; no tiene con qué comparar. La herida más profunda del dinero malo es esta: que termina siendo invisible para su última víctima, porque le llega convertida en sentido común.',

    'Esto es lo que el dinero falso le hace a un pueblo antes de hacerle nada visible: le acorta el horizonte. No le quema los bosques ni le vacía los suelos ni le financia las guerras —todavía no—. Primero le hace algo más callado y más grave: le cambia, a millones de personas a la vez, la respuesta a la única pregunta de la que cuelga todo lo demás —cuánto futuro vale la pena tener en cuenta—. Lo demás viene después, y viene solo. Una especie que dejó de mirar lejos talará, vaciará, quemará y se endeudará sin que haga falta empujarla, porque cada una de esas cosas es, en el fondo, lo que hace alguien para quien el mañana pesa menos de lo que debería.',

    'Por eso esta es la herida de la que cuelgan las demás, y por eso abre el bloque en vez de cerrarlo. Las consecuencias que vienen —el árbol que cae, la tierra que se agota, la mesa que se llena y no alimenta, la guerra que nadie pagaría de frente— no son seis problemas distintos con seis culpables distintos. Cada una tiene, es cierto, sus causas propias —y a su tiempo las nombraremos—. Pero todas comparten un suelo, y el dinero falso es ese suelo: no talla cada herida con su propia mano, pero inclina el piso bajo todas a la vez, de modo que todo rueda hacia el mismo lado. Son la misma cuenta falseada, inclinando seis pendientes distintas. Aprendimos a ver la primera, la que el joven toca con la mano. Vamos ahora a las otras, que están más lejos de la vista pero salen del mismo lugar —y que usted, cuando las reconozca, ya no podrá volver a mirar como problemas sueltos.',
]

# ---- Construir el HTML del article ----
parts = ['<article class="page" id="contenido" tabindex="-1">\n',
         f'\n  <div class="chapter-eyebrow">{EYEBROW}</div>\n',
         f'  <h1 class="chapter-title">{TITLE}</h1>\n',
         f'  <p class="chapter-subtitle">{SUBTITLE}</p>\n',
         '\n  <div class="ornament">• • •</div>\n',
         '\n  <div class="prose">\n']
for it in CONTENT:
    if isinstance(it, str):
        parts.append(f'    <p>{it}</p>\n')
    elif it[0] == "lead":
        parts.append(f'    <p class="lead">{it[1]}</p>\n')
parts.append('\n  </div>\n\n</article>')
article = ''.join(parts)

# ---- Esqueleto del cap 3 ----
sk = open('tres-regimenes.html', encoding='utf-8').read()
out = sk
out = re.sub(r'<title>.*?</title>',
             '<title>El horizonte se acorta — Arregla el dinero, arregla el mundo</title>',
             out, count=1, flags=re.DOTALL)
out = re.sub(r'<article class="page"[^>]*>.*?</article>', lambda _m: article, out, count=1, flags=re.DOTALL)
# nav-foot: prev=bisagra del oro; next=cap 16 «Comerse la semilla».
new_nav = ('<nav class="nav-foot">'
           '<a class="prev" href="por-que-no-volver-al-oro.html">¿Y por qué no volver al oro?</a>'
           '<a class="idx" href="index.html">Índice</a>'
           '<a class="next" href="comerse-la-semilla.html">Comerse la semilla</a></nav>')
out = re.sub(r'<nav class="nav-foot">.*?</nav>', lambda _m: new_nav, out, count=1, flags=re.DOTALL)
out = out.replace('audio/tres-regimenes.mp3', 'audio/el-horizonte-se-acorta.mp3')
out = out.replace('audio/tres-regimenes.alignment.json', 'audio/el-horizonte-se-acorta.alignment.json')
out = out.replace('data-storage-key="tres-regimenes"', 'data-storage-key="el-horizonte-se-acorta"')

open('el-horizonte-se-acorta.html', 'w', encoding='utf-8').write(out)
n_par = sum(1 for it in CONTENT if isinstance(it, str) or it[0] == "lead")
print("el-horizonte-se-acorta.html creado")
print(f"párrafos: {n_par}")
